-- 100 users registration SQL
-- This file contains SQL statements to insert 100 sample users

USE mydatabase;

-- Create users table if it doesn't exist
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    age INT,
    department VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert 100 users
INSERT INTO users (name, email, age, department) VALUES
('Alice Johnson', 'alice.johnson@example.com', 25, 'Engineering'),
('Bob Smith', 'bob.smith@example.com', 30, 'Marketing'),
('Carol Davis', 'carol.davis@example.com', 28, 'Sales'),
('David Wilson', 'david.wilson@example.com', 32, 'Engineering'),
('Emma Brown', 'emma.brown@example.com', 27, 'HR'),
('Frank Miller', 'frank.miller@example.com', 35, 'Finance'),
('Grace Lee', 'grace.lee@example.com', 26, 'Engineering'),
('Henry Garcia', 'henry.garcia@example.com', 29, 'Marketing'),
('Ivy Martinez', 'ivy.martinez@example.com', 31, 'Sales'),
('Jack Anderson', 'jack.anderson@example.com', 33, 'Engineering'),
('Kate Taylor', 'kate.taylor@example.com', 24, 'HR'),
('Liam Thomas', 'liam.thomas@example.com', 28, 'Finance'),
('Mia Jackson', 'mia.jackson@example.com', 30, 'Engineering'),
('Noah White', 'noah.white@example.com', 27, 'Marketing'),
('Olivia Harris', 'olivia.harris@example.com', 29, 'Sales'),
('Paul Clark', 'paul.clark@example.com', 34, 'Engineering'),
('Quinn Lewis', 'quinn.lewis@example.com', 25, 'HR'),
('Ruby Robinson', 'ruby.robinson@example.com', 32, 'Finance'),
('Sam Walker', 'sam.walker@example.com', 26, 'Engineering'),
('Tina Hall', 'tina.hall@example.com', 28, 'Marketing'),
('Uma Allen', 'uma.allen@example.com', 31, 'Sales'),
('Victor Young', 'victor.young@example.com', 33, 'Engineering'),
('Wendy King', 'wendy.king@example.com', 27, 'HR'),
('Xavier Wright', 'xavier.wright@example.com', 30, 'Finance'),
('Yara Lopez', 'yara.lopez@example.com', 25, 'Engineering'),
('Zoe Hill', 'zoe.hill@example.com', 29, 'Marketing'),
('Adam Green', 'adam.green@example.com', 32, 'Sales'),
('Beth Adams', 'beth.adams@example.com', 26, 'Engineering'),
('Carl Baker', 'carl.baker@example.com', 34, 'HR'),
('Dana Gonzalez', 'dana.gonzalez@example.com', 28, 'Finance'),
('Ethan Nelson', 'ethan.nelson@example.com', 31, 'Engineering'),
('Fiona Carter', 'fiona.carter@example.com', 27, 'Marketing'),
('George Mitchell', 'george.mitchell@example.com', 30, 'Sales'),
('Helen Perez', 'helen.perez@example.com', 33, 'Engineering'),
('Ian Roberts', 'ian.roberts@example.com', 25, 'HR'),
('Julia Turner', 'julia.turner@example.com', 29, 'Finance'),
('Kevin Phillips', 'kevin.phillips@example.com', 32, 'Engineering'),
('Luna Campbell', 'luna.campbell@example.com', 26, 'Marketing'),
('Mike Parker', 'mike.parker@example.com', 34, 'Sales'),
('Nina Evans', 'nina.evans@example.com', 28, 'Engineering'),
('Oscar Edwards', 'oscar.edwards@example.com', 31, 'HR'),
('Penny Collins', 'penny.collins@example.com', 27, 'Finance'),
('Quincy Stewart', 'quincy.stewart@example.com', 30, 'Engineering'),
('Rosa Sanchez', 'rosa.sanchez@example.com', 25, 'Marketing'),
('Steve Morris', 'steve.morris@example.com', 33, 'Sales'),
('Tara Rogers', 'tara.rogers@example.com', 29, 'Engineering'),
('Urban Reed', 'urban.reed@example.com', 32, 'HR'),
('Vera Cook', 'vera.cook@example.com', 26, 'Finance'),
('Wade Bailey', 'wade.bailey@example.com', 34, 'Engineering'),
('Xena Rivera', 'xena.rivera@example.com', 28, 'Marketing'),
('Yale Cooper', 'yale.cooper@example.com', 31, 'Sales'),
('Zara Richardson', 'zara.richardson@example.com', 27, 'Engineering'),
('Aaron Cox', 'aaron.cox@example.com', 30, 'HR'),
('Bella Howard', 'bella.howard@example.com', 25, 'Finance'),
('Colin Ward', 'colin.ward@example.com', 33, 'Engineering'),
('Delia Torres', 'delia.torres@example.com', 29, 'Marketing'),
('Eric Peterson', 'eric.peterson@example.com', 32, 'Sales'),
('Faith Gray', 'faith.gray@example.com', 26, 'Engineering'),
('Gary Ramirez', 'gary.ramirez@example.com', 34, 'HR'),
('Holly James', 'holly.james@example.com', 28, 'Finance'),
('Ivan Watson', 'ivan.watson@example.com', 31, 'Engineering'),
('Jade Brooks', 'jade.brooks@example.com', 27, 'Marketing'),
('Kyle Kelly', 'kyle.kelly@example.com', 30, 'Sales'),
('Leah Sanders', 'leah.sanders@example.com', 25, 'Engineering'),
('Marc Price', 'marc.price@example.com', 33, 'HR'),
('Nora Bennett', 'nora.bennett@example.com', 29, 'Finance'),
('Owen Wood', 'owen.wood@example.com', 32, 'Engineering'),
('Piper Barnes', 'piper.barnes@example.com', 26, 'Marketing'),
('Quest Ross', 'quest.ross@example.com', 34, 'Sales'),
('Rita Henderson', 'rita.henderson@example.com', 28, 'Engineering'),
('Sean Coleman', 'sean.coleman@example.com', 31, 'HR'),
('Tess Jenkins', 'tess.jenkins@example.com', 27, 'Finance'),
('Ulysses Perry', 'ulysses.perry@example.com', 30, 'Engineering'),
('Violet Powell', 'violet.powell@example.com', 25, 'Marketing'),
('Will Long', 'will.long@example.com', 33, 'Sales'),
('Xara Patterson', 'xara.patterson@example.com', 29, 'Engineering'),
('Yorick Hughes', 'yorick.hughes@example.com', 32, 'HR'),
('Zelda Flores', 'zelda.flores@example.com', 26, 'Finance'),
('Andre Washington', 'andre.washington@example.com', 34, 'Engineering'),
('Brooke Butler', 'brooke.butler@example.com', 28, 'Marketing'),
('Chase Simmons', 'chase.simmons@example.com', 31, 'Sales'),
('Daisy Foster', 'daisy.foster@example.com', 27, 'Engineering'),
('Eli Gonzales', 'eli.gonzales@example.com', 30, 'HR'),
('Faye Bryant', 'faye.bryant@example.com', 25, 'Finance'),
('Glen Alexander', 'glen.alexander@example.com', 33, 'Engineering'),
('Hope Russell', 'hope.russell@example.com', 29, 'Marketing'),
('Igor Griffin', 'igor.griffin@example.com', 32, 'Sales'),
('June Diaz', 'june.diaz@example.com', 26, 'Engineering'),
('Kane Hayes', 'kane.hayes@example.com', 34, 'HR'),
('Lily Myers', 'lily.myers@example.com', 28, 'Finance'),
('Max Ford', 'max.ford@example.com', 31, 'Engineering'),
('Nova Hamilton', 'nova.hamilton@example.com', 27, 'Marketing'),
('Otto Graham', 'otto.graham@example.com', 30, 'Sales'),
('Page Sullivan', 'page.sullivan@example.com', 25, 'Engineering'),
('Quill Wallace', 'quill.wallace@example.com', 33, 'HR'),
('Reed Woods', 'reed.woods@example.com', 29, 'Finance'),
('Sage Cole', 'sage.cole@example.com', 32, 'Engineering'),
('Toby West', 'toby.west@example.com', 26, 'Marketing'),
('Unity Jordan', 'unity.jordan@example.com', 34, 'Sales'),
('Vale Owens', 'vale.owens@example.com', 28, 'Engineering'),
('Wren Reynolds', 'wren.reynolds@example.com', 31, 'HR'),
('Xen Fisher', 'xen.fisher@example.com', 27, 'Finance'),
('York Ellis', 'york.ellis@example.com', 30, 'Engineering'),
('Zion Harper', 'zion.harper@example.com', 25, 'Marketing')
ON DUPLICATE KEY UPDATE name=VALUES(name);

-- Show the count of inserted users
SELECT COUNT(*) as total_users FROM users;
